# The base URL of the rageshake server, WITHOUT the `api/listing` suffix. This key/value is required.
server = "https://rageshake.server.com"

# The username and password for basic HTTP Auth with the rageshake server. These key/values are required.
username = "username"
password = "password"

# Technically how many tokio tasks you want to spawn when syncing the files;
# Can cause issues if you do around 100 or more, and I've found good performance
# when running with 50, so I'd recommend leaving it as is.
# This key/value is required.
threads = 50

# The only operating systems you want to download logs for.
# The possible options are 'ios', 'android', and 'desktop'. There can be multiple options,
# separated by commas like below.
# This key/value is not required, and can slow down sync significantly if you have a slow internet connection
sync-os = "android,desktop"

# Filter logs by only downloading logs before and/or after (respectively) the given dates
# Dates must be a single day, in ISO-8601 format, with day, month, and year.
# If these values are logically inconsistent or mutually exclusive, then simply no entries will sync.
# These key/values are not required, and will not slow down the syncing.
sync-before = "2021-07-01"
sync-after = "2021-07-20"
sync-when = "2021-07-10"

# If you should only sync logs from a specific user
# This is not required, and will slow down syncing dramatically if included.
sync-user = "john"

# Whether or not the server should download an entry anyways if it can't determine whether it fits the sync conditions above
# This key/value is not required, will not slow down the syncing, and defaults to `true` when not included.
sync-unsure = true

# If an entry needs to match only one condition to be synced, or if it needs to match all. If any is true, it only needs to match one.
# This is not required, and will default to false if not included.
sync-any = true

# Whether or not to use some slightly hacky methods to determine the OS of each entry when determining whether or not to sync them.
#
# When this is set to `false`, the server downloads the `details.log.gz` file for each entry which it needs the OS of and
# looks for the `Application: ` key in that file to determine the os. Obviously, this can cause syncing to be very slow on slower internet connections.
#
# When this is set to `true`, however, it determines the OS of each entry from the list of files contained in the entry.
# If there is one file, and it is called `details.log.gz`, the OS is determined to be `desktop`.
# If there is a file called `logs-0000.log.gz` in the entry, the OS is `android`.
# If there is a file called `console.log.gz` in the entry, the OS is `ios`.
# If none of these are true, if downloads the `details.log.gz` file anyways and parses that just like normal.
#
# This key/value is not required, and will default to `false` if not included.
beeper-hacks = false

# How many times to retry a sync where one or more files failed to download.
# If this key/value is not included, rager never retries a sync. If it is included and set to 0,
# rager will continue resyncing until all files are downloaded. Otherwise, it only retries as many times as is specified.
sync-retry-limit = 3
