# The base URL of the rageshake server. This key/value is required.
server = "https://rageshake.server.com"

# The username and password for basic HTTP Auth with the rageshake server. These key/values are required.
username = "username"
password = "password"

# Technically how many tokio tasks you want to spawn when syncing the files;
# Can cause issues if you do around 100 or more, and I've found good performance
# when running with 50, so I'd recommend leaving it as is.
# This key/value is required.
threads = 50

# The only operating systems you want to download logs for.
# The possible options are 'ios', 'android', and 'desktop'. There can be multiple options,
# separated by commas like below.
# This key/value is not required, and can slow down sync significantly if you have a slow internet connection
sync-os = "android,desktop"

# Filter logs by only downloading logs before and/or after (respectively) the given dates
# Dates must be a single day, in ISO-8601 format, with day, month, and year.
# These key/values are not required, and will not slow down the syncing.
sync-before = "2021-07-01"
sync-after = "2021-07-20"

# Whether or not the server should download an entry anyways if it can't determine whether it fits the sync conditions above
# This key/value is not required, and will not slow down the syncing.
ok-unsure = true
