name: "Build"
on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      profile_flag:
        description: Rust compilation profile flag
        default: --profile githubrelease
        required: true
        type: string
jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        build: [ darwin, darwin-arm, ubuntu, windows ]
        include:
          - build: darwin
            os: macos-latest
            target: x86_64-apple-darwin
          - build: darwin-arm
            os: macos-latest
            target: aarch64-apple-darwin
          - build: ubuntu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: .exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          profile: minimal
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build ${{ github.event.inputs.profile_flag }} 

      - name: Create Release
        uses: actions/upload-artifact@v3
        with:
          name: rager_${{ matrix.target }}
          path: target/${{ matrix.target }}/githubrelease/rager${{ matrix.extension }}
